# Generated by Django 5.0.2 on 2024-07-10 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running_text", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtext",
            name="background_color",
            field=models.CharField(
                default="#ff0000", max_length=7, null=True, verbose_name="Цвет текста"
            ),
        ),
        migrations.AddField(
            model_name="runtext",
            name="duration",
            field=models.IntegerField(
                default=3,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(2),
                    django.core.validators.MinValueValidator(10),
                ],
                verbose_name="Длительность",
            ),
        ),
        migrations.AddField(
            model_name="runtext",
            name="height",
            field=models.IntegerField(
                default=100,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(50),
                ],
                verbose_name="Высота",
            ),
        ),
        migrations.AddField(
            model_name="runtext",
            name="text_color",
            field=models.CharField(
                default="#ffffff", max_length=7, null=True, verbose_name="Цвет текста"
            ),
        ),
        migrations.AddField(
            model_name="runtext",
            name="text_size",
            field=models.IntegerField(
                default=40,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(100),
                ],
                verbose_name="Размер текста",
            ),
        ),
        migrations.AddField(
            model_name="runtext",
            name="width",
            field=models.IntegerField(
                default=100,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(50),
                ],
                verbose_name="Ширина",
            ),
        ),
    ]
