# Generated by Django 5.0.2 on 2024-07-10 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running_text", "0002_runtext_background_color_runtext_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtext",
            name="background_color",
            field=models.CharField(
                default="#ff0000", max_length=7, null=True, verbose_name="Цвет фона"
            ),
        ),
        migrations.AlterField(
            model_name="runtext",
            name="duration",
            field=models.IntegerField(
                default=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Длительность",
            ),
        ),
        migrations.AlterField(
            model_name="runtext",
            name="height",
            field=models.IntegerField(
                default=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="runtext",
            name="text_size",
            field=models.IntegerField(
                default=40,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Размер текста",
            ),
        ),
        migrations.AlterField(
            model_name="runtext",
            name="width",
            field=models.IntegerField(
                default=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Ширина",
            ),
        ),
    ]
