# Generated by Django 5.0.2 on 2024-07-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("running_text", "0003_alter_runtext_background_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runtext",
            old_name="text_size",
            new_name="font_size",
        ),
    ]
