# Generated by Django 5.0.2 on 2024-07-10 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running_text", "0004_rename_text_size_runtext_font_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtext",
            name="font_size",
            field=models.IntegerField(
                default=40,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Размер текста",
            ),
        ),
    ]
